name: Build and Push New
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gen-moderator
      PROJECT_ID: flowing-scholar-387113
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get the tag name
      id: get_tag_name
      run: |
        short_sha=$(echo $GITHUB_SHA | head -c 7)
        echo "IMAGE_TAG=${GITHUB_REF_NAME}-${short_sha}" >> $GITHUB_ENV
        echo "BUILD_ENV=${GITHUB_REF_NAME}" >> $GITHUB_ENV

    - name: Setup google auth
      id: "auth"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet gcr.io

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          gcr.io/$PROJECT_ID/${{env.IMAGE_NAME}}:latest
          gcr.io/$PROJECT_ID/${{env.IMAGE_NAME}}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ENV=${{ env.BUILD_ENV }}