name: Docker develops build

on:
  push:
    branches:
      - "staging"
      - "develop"
      - "develop_api"
      - "develop_ai_school"

env:
  DOCKER_REGISTRY: asia-docker.pkg.dev
  DOCKER_IMAGE_NAME: flowing-scholar-387113/gen-moderator
  DOCKERFILE_NAME: Dockerfile

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    concurrency:
      group: build_develop
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - name: Get the tag name
        id: get_tag_name
        run: |
          short_sha=$(echo $GITHUB_SHA | head -c 7)
          echo "IMAGE_TAG=${GITHUB_REF_NAME}-${short_sha}" >> $GITHUB_ENV
          echo "BUILD_ENV=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Use ai-school.Dockerfile
        id: set_dockerfile_ai_school
        if: endsWith(github.ref, '_ai_school')
        run: |
          echo "DOCKERFILE_NAME=ai-school.Dockerfile" >> $GITHUB_ENV

      - name: Setup google auth
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push
        with:
          context: .
          file: ${{env.DOCKERFILE_NAME}}
          push: true
          run: |
            docker tag ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_IMAGE_NAME}}:latest
            docker push ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_IMAGE_NAME}}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ENV=${{ env.BUILD_ENV }}
